"""upgrade_users_table

Revision ID: 154d385b9608
Revises: 2c0c6351341a
Create Date: 2023-01-10 22:06:33.750729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154d385b9608'
down_revision = '2c0c6351341a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
