"""cascade deletion in revievs

Revision ID: 245b7b9b03cb
Revises: 961093b9aef7
Create Date: 2023-03-12 23:07:17.260023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245b7b9b03cb'
down_revision = '961093b9aef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
