"""upd reviews

Revision ID: 5007b815f84c
Revises: 3581d71d0f64
Create Date: 2023-01-17 21:23:24.509564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5007b815f84c'
down_revision = '3581d71d0f64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('review_user_id_fkey', 'review', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
