"""cascade deletion in reviev

Revision ID: 5f389b725d94
Revises: 245b7b9b03cb
Create Date: 2023-03-12 23:08:31.857994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f389b725d94'
down_revision = '245b7b9b03cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_tag_tag_id_fkey', 'review_tag', type_='foreignkey')
    op.drop_constraint('review_tag_review_id_fkey', 'review_tag', type_='foreignkey')
    op.create_foreign_key(None, 'review_tag', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_tag', type_='foreignkey')
    op.drop_constraint(None, 'review_tag', type_='foreignkey')
    op.create_foreign_key('review_tag_review_id_fkey', 'review_tag', 'review', ['review_id'], ['id'])
    op.create_foreign_key('review_tag_tag_id_fkey', 'review_tag', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
