"""upgrade users

Revision ID: 95334b487a31
Revises: d3947d1711b9
Create Date: 2023-01-21 20:27:56.005807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95334b487a31'
down_revision = 'd3947d1711b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
