"""upd tags table

Revision ID: 9a0b5292decc
Revises: a4be042bc340
Create Date: 2023-01-22 04:25:15.871832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0b5292decc'
down_revision = 'a4be042bc340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('review_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'review_id')
    # ### end Alembic commands ###
