"""upd tags table

Revision ID: cbe1ff668d03
Revises: 9a0b5292decc
Create Date: 2023-01-22 04:55:08.617150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe1ff668d03'
down_revision = '9a0b5292decc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tag', 'review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    # ### end Alembic commands ###
